### ISSUE TITLE
Demo on H. pylori is down

### ISSUE THREAD

**Issue by SingingMeerkat** [mjsull/chromatiblock#16]
Hello,

As said in the title, the demo for H. pylori linked in your ReadMe is down; it returns an error 404 when following the link on your ReadMe (supposedly redirecting toward https://mjsull.github.com/chromatiblock/H_pylori.html ).

Is there any other demo available somewhere?

Thank you!

**Comment by mjsull** [comment]
Hi @SingingMeerkat,

Githhub seems to have gotten rid of .com personal pages, fixed now :)

You can view it here.

https://mjsull.github.io/chromatiblock/H_pylori.html
