### ISSUE TITLE
Consider renaming script to "chromatiblock"

### ISSUE THREAD

**Issue by tseemann** [mjsull/chromatiblock#2]
Looks more professional?
And matches repo name
and run as `chromatiblock` rather than `python Chromatiblock.py`
you know, in case you rewrite it in Perl one day :-P

**Comment by tseemann** [comment]
![image](https://user-images.githubusercontent.com/453972/66964644-f4a0a080-f0c2-11e9-9443-822af236b6d4.png)

**Comment by mjsull** [comment]
ahhh, haha I missed the dropping of the ".py" and just changed the capital "C".

Will fix in next update.
