### ISSUE TITLE
Problem with cariosvg

### ISSUE THREAD

**Issue by mjsull** [mjsull/chromatiblock#7]
I've narrowed it down to a particular genome (B_erythrophleiGAS401.fna) from NCBI that is causing it to error. Here is a smaller dataset of two genomes that gives a similar error using the newest version of chromatiblock. The output I get is in the output file, also posted here:

./chromatiblock -w ./ -o image.pdf -d ./

output:

Simplification stage 1 of 4
Enumerating vertices of the graph, then performing bulge removal...
[..................................................]
Simplification stage 2 of 4
Enumerating vertices of the graph, then performing bulge removal...
[..................................................]
Simplification stage 3 of 4
Enumerating vertices of the graph, then performing bulge removal...
[..................................................]
Simplification stage 4 of 4
Enumerating vertices of the graph, then performing bulge removal...
[..................................................]
Finding synteny blocks and generating the output...
Traceback (most recent call last):
  File "/local/cluster/lib/python3.7/xml/etree/ElementTree.py", line 1630, in feed
    self.parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 3, column 9

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./chromatiblock", line 1555, in <module>
    draw_blocks(core_array, noncore_pos, core_size, args.out, args.genome_height, args.gap, legend_size, args.working_directory, args.ppi, args.categorise != None, args.svg_pan_zoom_location, args.hue_start, args.hue_end)
  File "./chromatiblock", line 1351, in draw_blocks
    cairosvg.svg2pdf(url=os.path.join(working_dir, "temp.svg"), write_to=out_file, dpi=ppi)
  File "/local/cluster/lib/python3.7/site-packages/cairosvg/__init__.py", line 80, in svg2pdf
    output_height=output_height)
  File "/local/cluster/lib/python3.7/site-packages/cairosvg/surface.py", line 144, in convert
    **kwargs)
  File "/local/cluster/lib/python3.7/site-packages/cairosvg/parser.py", line 407, in __init__
    forbid_external=not unsafe)
  File "/local/cluster/lib/python3.7/site-packages/defusedxml/common.py", line 131, in fromstring
    parser.feed(text)
  File "/local/cluster/lib/python3.7/xml/etree/ElementTree.py", line 1632, in feed
    self._raiseerror(v)
  File "/local/cluster/lib/python3.7/xml/etree/ElementTree.py", line 1531, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 3, column 9

Thanks!

[testdataset.tar.gz](https://github.com/mjsull/chromatiblock/files/4081381/testdataset.tar.gz)

_Originally posted by @alexweisberg in https://github.com/mjsull/chromatiblock/issues/6#issuecomment-575925725_

**Comment by mjsull** [comment]
Hi,

These seem to be two separate issues.

This seems to be a problem with the package I'm using to create a PDF, I'll raise the issue with the developers of that package, but it will probably be a while before this can be fixed.

In the mean time, it might be easier to create and SVG and then covert it to PDF with something like Inkscape, which is a nice, free application for editing SVG files.

Best,

Mitch

**Comment by alexweisberg** [comment]
Hi,

I reran the analysis and produced an image.svg instead. However when I tried to visualize it in inkscape it crashed, and when I open it in firefox I get the error:
`XML Parsing Error: not well-formed
Location: file:///Users/alexandraweisberg/Research/Postdoc/bradyrhizobium/nanopore/chromatiblock/image.svg`
`Line Number 3, Column 10:`
` <a href=image.svg_files/0.html>  <rect stroke="#5b0a0a" stroke-opacity="1.000000" stroke-alignment="inner" `
`---------^`

If I rename the file from image.svg to image.svg.hml, it mostly loads in firefox but large portions are blank (see attached screenshot). I've put a link to the svg output[ here](http://files.cgrb.oregonstate.edu/Botany/Chang_Lab/chromatiblockexample/image.svg). Thank you again for helping get this running.

Best,
Alex
![image svg html_example](https://user-images.githubusercontent.com/12143265/73011210-a89f7f00-3dc8-11ea-922b-c79e6d4c366a.png)

**Comment by mjsull** [comment]
Hi Alex,

It looks like there is very little "core" genome between all your samples. Are they from the same genus? Potentially one bad assembly/genome may be ruining the alignment?

If that's not the case, setting `--sibelia_mode far` should help with isolates that are a little more distant.

Best,

Mitchell

**Comment by alexweisberg** [comment]
Hi,

They are the same genus, however the genus is pretty diverse, so I'm guess its due to that. I will try a smaller dataset and see where it starts to get messy. I will also try the sibelia option too. Thanks!

Best,
Alex
