### ISSUE TITLE
Genome name labels in the interactive plot

### ISSUE THREAD

**Issue by calvinnacaswara** [mjsull/chromatiblock#9]
Hi, again not an issue but a recommendation for the interactive plot: Maybe the genome names could be listed on the left side of the MSA and colinear-blocks ? This way I don't always have to look up the order.

**Comment by mjsull** [comment]
Hovering your cursor above a block will show a contig name. I've also added a flag to add the FASTA names as labels.

**Comment by fwhelan** [comment]
Hi mjsull. I'm struggling to get the FASTA name labels to show in my html outputs. I've tried `-t`, `--show_fasta_labels` (as per #10), and `--show_labels` (as per main page documentation, but this appears to be a typo as I get an argument not found error). I've made sure that my contig names are unique incase that mattered, fasta file names are unique. I can see the unique contig names in the cursor hover over, but labels would be helpful.

Thank you!
